name: Deploy react app to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: 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
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: build
